Handle mkfifo failure

diff --git a/backcheck b/backcheck
--- a/backcheck
+++ b/backcheck
@@ -161,7 +161,12 @@ endTime=$(((startTime + timeout)))
 
 rcharBefore="$(grep -oP '(?<=rchar: ).*' /proc/$$/io)"
 
-mkfifo --mode=600 /tmp/backcheck-$$-backup-sum /tmp/backcheck-$$-source-sum
+if ! mkfifo --mode=600 /tmp/backcheck-$$-backup-sum /tmp/backcheck-$$-source-sum 2>/dev/null; then
+	echo "Could not create named pipes /tmp/backcheck-$$-backup-sum /tmp/backcheck-$$-source-sum, aborting."
+
+	exit 1
+fi
+
 for i in $(shuf -i 0-$(((backupFilesCount - 1)))); do
 	if [ "$timeout" -gt 0 ]; then
 		if [ "$endTime" -lt "$(date +"%s")" ]; then
