Fix for CentOS 7

diff --git a/backcheck b/backcheck
--- a/backcheck
+++ b/backcheck
@@ -39,12 +39,24 @@ if [ "$1" == "--help" ]; then
 	exit 0
 fi
 
+backupPath="${*: -2:1}"
+sourcePath="${*: -1}"
+
+if [ ! -d "$backupPath" ]; then
+	echo "Backup directory '$backupPath' doesn't exist, aborting."
+
+	exit 1
+fi
+if [ ! -d "$sourcePath" ]; then
+	echo "Source directory '$sourcePath' doesn't exist, aborting."
+
+	exit 1
+fi
+
 # If possible, call ourselves in bwrap with the source and backup paths read only again
 # that way we can ensure to not alter the file's atime.
 if [ ! "$1" == "--postwrap" ] && [ -f "$0" ] && command -v bwrap >/dev/null 2>&1; then
-	backupPath="${*: -2:1}"
-	sourcePath="${*: -1}"
-	exec bwrap --dev-bind / / --ro-bind-try "$backupPath" "$backupPath" --ro-bind-try "$sourcePath" "$sourcePath" "$0" --postwrap "$@"
+	exec bwrap --dev-bind / / --ro-bind "$backupPath" "$backupPath" --ro-bind "$sourcePath" "$sourcePath" "$0" --postwrap "$@"
 elif [ "$1" == "--postwrap" ]; then
 	shift
 fi
@@ -71,22 +83,11 @@ while [ $# -gt 2 ]; do
 	esac
 done
 
-if [ ! -d "$1" ]; then
-	echo "Backup directory '$1' doesn't exist, aborting."
-
-	exit 1
-fi
-if [ ! -d "$2" ]; then
-	echo "Source directory '$2' doesn't exist, aborting."
-
-	exit 1
-fi
-
 # Derived from https://stackoverflow.com/a/23357277
 backupFiles=()
 while IFS=  read -r -d $'\0'; do
 	backupFiles+=("$REPLY")
-done < <(find "$1" -type f -print0)
+done < <(find "$backupPath" -type f -print0)
 
 backupFilesCount="${#backupFiles[@]}"
 if [ "$backupFilesCount" -eq 0 ]; then
@@ -109,10 +110,10 @@ for i in $(shuf -i 0-$(((backupFilesCount - 1)))); do
 			break
 		fi
 	fi
-	((( processed++ )))
+	(( processed++ ))
 
 	backupFile="${backupFiles[$i]}"
-	sourceFile="${backupFile/"$1"/$2}"
+	sourceFile="${backupFile/"$backupPath"/$sourcePath}"
 	if [ $debug -gt 0 ]; then
 		echo -e "\nChecking '$backupFile' <> '$sourceFile'."
 	fi
